- name: "Common Setup"
  hosts: all:!localhost
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: 'common'

- name: "Common Kubernetes Setup"
  hosts: "masters, workers"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "k8s-common"

- name: "Master Kubernetes Setup"
  hosts: "masters"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "k8s-control-plane"
      vars:
        skip_phases: "{% if cni == 'cilium'%}addon/kube-proxy{% endif %}"
    - role: "k8s-argo-cd"
      vars:
        kubeconfig: ./.kubeconfig.yaml
        bootstrap_repo_url: "{{ argo_cd_bootstrap_repo_url }}"
        domain: "{{ argo_cd_cluster_domain }}"
    - role: "nfs-server"
      vars:
        path: /data
  tasks:
    - name: Untaint
      kubernetes.core.k8s_taint:
        state: absent
        kubeconfig: ./.kubeconfig.yaml
        name: "{{ ansible_facts['hostname'] }}"
        taints:
          - key: node-role.kubernetes.io/control-plane
      delegate_to: localhost
