- name: "Common Setup"
  hosts: all:!localhost
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "common"
      vars:
        user: "{{ users }}"

- name: "GPU Setup"
  hosts: all:!localhost
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "gpu"

- name: "Common Kubernetes Setup"
  hosts: "masters, workers"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "k8s-common"

- name: "Master Kubernetes Setup"
  hosts: "masters"
  become: true
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: true
  connection: ssh
  roles:
    - role: "k8s-control-plane"
      vars:
        skip_phases: "{% if cni == 'cilium'%}addon/kube-proxy{% endif %}"
    - role: "k8s-argo-cd"
      vars:
        kubeconfig: ./.kubeconfig.yaml
        bootstrap_application: "{{ argo_cd_bootstrap_application }}"
    - role: "nfs-server"
      vars:
        path: /data
        mount_device: /dev/md0
  tasks:
    - name: Untaint
      kubernetes.core.k8s_taint:
        state: absent
        kubeconfig: ./.kubeconfig.yaml
        name: "{{ ansible_facts['hostname'] }}"
        taints:
          - key: node-role.kubernetes.io/control-plane
      delegate_to: localhost

    - name: Remove exclude-from-external-load-balancers
      kubernetes.core.k8s:
        state: patched
        kind: Node
        name: "{{ ansible_facts['hostname'] }}"
        definition:
          metadata:
            labels:
              node.kubernetes.io/exclude-from-external-load-balancers: NULL
      delegate_to: localhost
