---
- name: Add ArgoCD helm chart repo
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: argo-cd
    repo_url: "https://argoproj.github.io/argo-helm"
  delegate_to: localhost

- name: Install ArgoCD from helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: argo-cd
    chart_ref: argo-cd/argo-cd
    release_namespace: argo-cd
    create_namespace: true
    values:
      dex:
        enabled: false
      notifications:
        enabled: false
      applicationSet:
        enabled: false
  delegate_to: localhost

- name: Adding bootstrap chart
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: argoproj.io/v1alpha1
      kind: Application
      metadata:
        name: bootstrap
        namespace: argo-cd
      spec:
        destination:
          namespace: argo-cd
          server: https://kubernetes.default.svc
        project: default
        source:
          path: "{{ bootstrap_repo_path }}"
          repoURL: "{{ bootstrap_repo_url }}"
          targetRevision: HEAD
          helm:
            parameters:
              - name: domain
                value: "{{ domain }}"
              - name: mail_address
                value: "{{ mail_address }}"
        syncPolicy:
          automated: {}
  delegate_to: localhost
