- name: Add flannel helm chart repo
  kubernetes.core.helm_repository:
    kubeconfig: "{{ kubeconfig }}"
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/
  delegate_to: localhost

- name: Install flannel from helm
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: kube-flannel
    create_namespace: true
    values:
      podCidr: "{{ pod_networking_cidr }}"
  delegate_to: localhost
