---
- name: Kubeadm init
  ansible.builtin.command:
    argv:
      - kubeadm
      - init
      - --pod-network-cidr={{ pod_networking_cidr }}
      - --skip-phases={{ skip_phases }}
#    cmd: kubeadm init --skip-phases=addon/kube-proxy
    #cmd: "kubeadm init {{ kubeadm_init_args }}"
    #cmd: kubeadm init --pod-network-cidr=10.244.0.0/16
    creates: /etc/kubernetes/kubelet.conf

- name: Create .kube directory
  file:
    path: .kube
    state: directory
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"

- name: Copy Kubeconfig
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: .kube/config
    owner: "{{ ansible_user | default(ansible_user_id) }}"
    group: "{{ ansible_user | default(ansible_user_id) }}"
    mode: 0600
    remote_src: true

- name: Fetch Kubeconfig
  ansible.builtin.fetch:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubeconfig }}"
    flat: true

- name: Install cni
  include_tasks: cni.yaml


