---
- name: Upgrade
  ansible.builtin.apt:
    upgrade: safe
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    pkg:
      - python3-debian
      - htop
      - vim
      - net-tools
      - inetutils-ping
      - git
      - curl
      - dnsutils
      - zsh

- name: Setup user accounts
  ansible.builtin.user:
    name: "{{ item.username }}"
    shell: "{{ item.shell }}"
  loop: "{{ users }}"

- name: Fetch authorized keys from github
  ansible.posix.authorized_key:
    user: "{{ item.username }}"
    state: present
    key: "https://github.com/{{ item.github_user }}.keys"
  loop: "{{ users }}"
  when: '"github_user" in item'

- name: Add sudo privilegues
  community.general.sudoers:
    name: "{{ item.username }}"
    state: "{% if 'sudo' in item and item.sudo %}present{% else %}absent{% endif %}"
    user: "{{ item.username }}"
    commands: ALL
  loop: "{{ users }}"
